apiVersion: v1
kind: Pod
metadata:
  name: pod-volumedinamico
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: volume-dinamico
          mountPath: /usr/share/nginx/html
  
  volumes:
    - name: volume-dinamico
      persistentVolumeClaim:
        claimName: pvc-dinamico