apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor-green
spec:
  selector:
    matchLabels:
      app: webcolor
      version: green
  template:
    metadata:
      labels:
        app: webcolor
        version: green
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:green
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
