apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: producao
servers: 1
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6445"
ports:
  - port: 8200:80
    nodeFilters:
      - loadbalancer
  - port: 8243:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
