apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: desenvolvimento
servers: 1
agents: 1
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: 8000:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
  - port: 3000:3000
    nodeFilters:
      - loadbalancer
  - port: 3001:3001
    nodeFilters:
      - loadbalancer
  - port: 3002:3002
    nodeFilters:
      - loadbalancer
  - port: 8001:8001
    nodeFilters:
      - loadbalancer
  - port: 8002:8002
    nodeFilters:
      - loadbalancer
  - port: 30000:30000
    nodeFilters:
      - agent:*
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
