apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homologacao
servers: 1
agents: 1
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6444"
ports:
  - port: 8100:80
    nodeFilters:
      - loadbalancer
  - port: 8143:443
    nodeFilters:
      - loadbalancer
  - port: 3100:3000
    nodeFilters:
      - loadbalancer
  - port: 3101:3001
    nodeFilters:
      - loadbalancer
  - port: 3102:3002
    nodeFilters:
      - loadbalancer
  - port: 8101:8001
    nodeFilters:
      - loadbalancer
  - port: 8102:8002
    nodeFilters:
      - loadbalancer
  - port: 30100:30000
    nodeFilters:
      - agent:*
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
