apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-chaos
  template:
    metadata:
      labels:
        app: simulador-chaos
    spec:
      containers:
      - name: simulador-chaos
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
          terminationGracePeriodSeconds: 30
        readinessProbe:
          httpGet:
            port: 3000
            path: /ready
            httpHeaders:
              - name: token
                value: "123456"
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            port: 3000
            path: /health
          failureThreshold: 30 # => 300s = 5min
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"