apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: registry.k8s.io/busybox
        command:
          - /bin/sh 
          - -c 
        args:
          - touch /tmp/heath; sleep 600;
        ports:
        - containerPort: 3000
        livenessProbe:
          exec:
            command: 
              - cat
              - /tmp/health
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
          terminationGracePeriodSeconds: 30