apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor-blue
spec:
  selector:
    matchLabels:
      app: webcolor
      version: blue
  template:
    metadata:
      labels:
        app: webcolor
        version: blue
    spec:
      containers:
      - name: web
        image: kubedevio/web-color:blue
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
