apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: pauloaragaodev/conversao-temperatura:v2
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP